// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terra/feeburn/v1/events.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Event fired when fees are burned with the amount of fees burned
type FeeBurnEvent struct {
	// Amount of the payout
	FeesBurn []types.Coin `protobuf:"bytes,1,rep,name=fees_burn,json=feesBurn,proto3" json:"fees_burn"`
}

func (m *FeeBurnEvent) Reset()         { *m = FeeBurnEvent{} }
func (m *FeeBurnEvent) String() string { return proto.CompactTextString(m) }
func (*FeeBurnEvent) ProtoMessage()    {}
func (*FeeBurnEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6c4b84def882b33, []int{0}
}
func (m *FeeBurnEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeBurnEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeBurnEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeBurnEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeBurnEvent.Merge(m, src)
}
func (m *FeeBurnEvent) XXX_Size() int {
	return m.Size()
}
func (m *FeeBurnEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeBurnEvent.DiscardUnknown(m)
}

var xxx_messageInfo_FeeBurnEvent proto.InternalMessageInfo

func (m *FeeBurnEvent) GetFeesBurn() []types.Coin {
	if m != nil {
		return m.FeesBurn
	}
	return nil
}

func init() {
	proto.RegisterType((*FeeBurnEvent)(nil), "terra.feeburn.v1.FeeBurnEvent")
}

func init() { proto.RegisterFile("terra/feeburn/v1/events.proto", fileDescriptor_f6c4b84def882b33) }

var fileDescriptor_f6c4b84def882b33 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xcf, 0x31, 0x4b, 0xc4, 0x30,
	0x14, 0x07, 0xf0, 0x16, 0x45, 0xb4, 0x3a, 0xc8, 0xe1, 0xa0, 0x07, 0x46, 0x71, 0x72, 0xf1, 0x3d,
	0x72, 0xae, 0x4e, 0x15, 0xc5, 0xc1, 0xc9, 0xd1, 0x45, 0x9a, 0xf0, 0xae, 0x76, 0x68, 0xde, 0x91,
	0xa4, 0xc1, 0xfb, 0x16, 0x7e, 0xac, 0x1b, 0x6f, 0x74, 0x12, 0x69, 0xbf, 0x88, 0x24, 0x2d, 0xb7,
	0x3d, 0xf2, 0xe7, 0xff, 0xe3, 0x9f, 0xe2, 0xd2, 0x93, 0xb5, 0x15, 0x2e, 0x89, 0x54, 0x67, 0x0d,
	0x06, 0x89, 0x14, 0xc8, 0x78, 0x07, 0x2b, 0xcb, 0x9e, 0x67, 0xa7, 0x29, 0x86, 0x29, 0x86, 0x20,
	0xe7, 0x42, 0xb3, 0x6b, 0xd9, 0xa1, 0xaa, 0x1c, 0x61, 0x90, 0x8a, 0x7c, 0x25, 0x51, 0x73, 0x63,
	0xc6, 0xc6, 0xfc, 0xac, 0xe6, 0x9a, 0xd3, 0x89, 0xf1, 0x1a, 0x5f, 0x6f, 0x5e, 0x8b, 0x93, 0x67,
	0xa2, 0xb2, 0xb3, 0xe6, 0x29, 0xf2, 0xb3, 0x87, 0xe2, 0x68, 0x49, 0xe4, 0x3e, 0xa2, 0x7a, 0x9e,
	0x5f, 0xef, 0xdd, 0x1e, 0x2f, 0x2e, 0x60, 0x94, 0x21, 0xca, 0x30, 0xc9, 0xf0, 0xc8, 0x8d, 0x29,
	0xf7, 0x37, 0xbf, 0x57, 0xd9, 0xdb, 0x61, 0x6c, 0x44, 0xa2, 0x7c, 0xd9, 0xf4, 0x22, 0xdf, 0xf6,
	0x22, 0xff, 0xeb, 0x45, 0xfe, 0x3d, 0x88, 0x6c, 0x3b, 0x88, 0xec, 0x67, 0x10, 0xd9, 0x3b, 0xd4,
	0x8d, 0xff, 0xec, 0x14, 0x68, 0x6e, 0x31, 0x4d, 0xbf, 0x6b, 0xd9, 0xd0, 0x1a, 0x35, 0x5b, 0xc2,
	0xb0, 0xc0, 0xaf, 0xdd, 0x4f, 0xfd, 0x7a, 0x45, 0x4e, 0x1d, 0xa4, 0x79, 0xf7, 0xff, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xbb, 0x3e, 0xfd, 0xb8, 0x07, 0x01, 0x00, 0x00,
}

func (m *FeeBurnEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeBurnEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeBurnEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeesBurn) > 0 {
		for iNdEx := len(m.FeesBurn) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeesBurn[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvents(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeBurnEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.FeesBurn) > 0 {
		for _, e := range m.FeesBurn {
			l = e.Size()
			n += 1 + l + sovEvents(uint64(l))
		}
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeBurnEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeBurnEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeBurnEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeesBurn", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeesBurn = append(m.FeesBurn, types.Coin{})
			if err := m.FeesBurn[len(m.FeesBurn)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
