// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terra/smartaccount/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateSmartAccount struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *MsgCreateSmartAccount) Reset()         { *m = MsgCreateSmartAccount{} }
func (m *MsgCreateSmartAccount) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSmartAccount) ProtoMessage()    {}
func (*MsgCreateSmartAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2931e7b90fb4027, []int{0}
}
func (m *MsgCreateSmartAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateSmartAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateSmartAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateSmartAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSmartAccount.Merge(m, src)
}
func (m *MsgCreateSmartAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateSmartAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSmartAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSmartAccount proto.InternalMessageInfo

func (m *MsgCreateSmartAccount) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type MsgCreateSmartAccountResponse struct {
}

func (m *MsgCreateSmartAccountResponse) Reset()         { *m = MsgCreateSmartAccountResponse{} }
func (m *MsgCreateSmartAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSmartAccountResponse) ProtoMessage()    {}
func (*MsgCreateSmartAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2931e7b90fb4027, []int{1}
}
func (m *MsgCreateSmartAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateSmartAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateSmartAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateSmartAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSmartAccountResponse.Merge(m, src)
}
func (m *MsgCreateSmartAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateSmartAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSmartAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSmartAccountResponse proto.InternalMessageInfo

type MsgAuthorization struct {
	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	InitMsg         string `protobuf:"bytes,2,opt,name=init_msg,json=initMsg,proto3" json:"init_msg,omitempty"`
}

func (m *MsgAuthorization) Reset()         { *m = MsgAuthorization{} }
func (m *MsgAuthorization) String() string { return proto.CompactTextString(m) }
func (*MsgAuthorization) ProtoMessage()    {}
func (*MsgAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2931e7b90fb4027, []int{2}
}
func (m *MsgAuthorization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAuthorization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuthorization.Merge(m, src)
}
func (m *MsgAuthorization) XXX_Size() int {
	return m.Size()
}
func (m *MsgAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuthorization proto.InternalMessageInfo

func (m *MsgAuthorization) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *MsgAuthorization) GetInitMsg() string {
	if m != nil {
		return m.InitMsg
	}
	return ""
}

type MsgAuthorizationResponse struct {
}

func (m *MsgAuthorizationResponse) Reset()         { *m = MsgAuthorizationResponse{} }
func (m *MsgAuthorizationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAuthorizationResponse) ProtoMessage()    {}
func (*MsgAuthorizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2931e7b90fb4027, []int{3}
}
func (m *MsgAuthorizationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAuthorizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAuthorizationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAuthorizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAuthorizationResponse.Merge(m, src)
}
func (m *MsgAuthorizationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAuthorizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAuthorizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAuthorizationResponse proto.InternalMessageInfo

type MsgUpdateAuthorization struct {
	Account       string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Fallback      bool     `protobuf:"varint,2,opt,name=fallback,proto3" json:"fallback,omitempty"`
	Authorization []string `protobuf:"bytes,3,rep,name=authorization,proto3" json:"authorization,omitempty"`
}

func (m *MsgUpdateAuthorization) Reset()         { *m = MsgUpdateAuthorization{} }
func (m *MsgUpdateAuthorization) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAuthorization) ProtoMessage()    {}
func (*MsgUpdateAuthorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2931e7b90fb4027, []int{4}
}
func (m *MsgUpdateAuthorization) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAuthorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAuthorization.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAuthorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAuthorization.Merge(m, src)
}
func (m *MsgUpdateAuthorization) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAuthorization) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAuthorization.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAuthorization proto.InternalMessageInfo

func (m *MsgUpdateAuthorization) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MsgUpdateAuthorization) GetFallback() bool {
	if m != nil {
		return m.Fallback
	}
	return false
}

func (m *MsgUpdateAuthorization) GetAuthorization() []string {
	if m != nil {
		return m.Authorization
	}
	return nil
}

type MsgUpdateAuthorizationResponse struct {
}

func (m *MsgUpdateAuthorizationResponse) Reset()         { *m = MsgUpdateAuthorizationResponse{} }
func (m *MsgUpdateAuthorizationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAuthorizationResponse) ProtoMessage()    {}
func (*MsgUpdateAuthorizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2931e7b90fb4027, []int{5}
}
func (m *MsgUpdateAuthorizationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAuthorizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAuthorizationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAuthorizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAuthorizationResponse.Merge(m, src)
}
func (m *MsgUpdateAuthorizationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAuthorizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAuthorizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAuthorizationResponse proto.InternalMessageInfo

type MsgUpdateTransactionHooks struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	PreTransactionHooks  []string `protobuf:"bytes,2,rep,name=pre_transaction_hooks,json=preTransactionHooks,proto3" json:"pre_transaction_hooks,omitempty"`
	PostTransactionHooks []string `protobuf:"bytes,3,rep,name=post_transaction_hooks,json=postTransactionHooks,proto3" json:"post_transaction_hooks,omitempty"`
}

func (m *MsgUpdateTransactionHooks) Reset()         { *m = MsgUpdateTransactionHooks{} }
func (m *MsgUpdateTransactionHooks) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateTransactionHooks) ProtoMessage()    {}
func (*MsgUpdateTransactionHooks) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2931e7b90fb4027, []int{6}
}
func (m *MsgUpdateTransactionHooks) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateTransactionHooks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateTransactionHooks.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateTransactionHooks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateTransactionHooks.Merge(m, src)
}
func (m *MsgUpdateTransactionHooks) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateTransactionHooks) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateTransactionHooks.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateTransactionHooks proto.InternalMessageInfo

func (m *MsgUpdateTransactionHooks) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MsgUpdateTransactionHooks) GetPreTransactionHooks() []string {
	if m != nil {
		return m.PreTransactionHooks
	}
	return nil
}

func (m *MsgUpdateTransactionHooks) GetPostTransactionHooks() []string {
	if m != nil {
		return m.PostTransactionHooks
	}
	return nil
}

type MsgUpdateTransactionHooksResponse struct {
}

func (m *MsgUpdateTransactionHooksResponse) Reset()         { *m = MsgUpdateTransactionHooksResponse{} }
func (m *MsgUpdateTransactionHooksResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateTransactionHooksResponse) ProtoMessage()    {}
func (*MsgUpdateTransactionHooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2931e7b90fb4027, []int{7}
}
func (m *MsgUpdateTransactionHooksResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateTransactionHooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateTransactionHooksResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateTransactionHooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateTransactionHooksResponse.Merge(m, src)
}
func (m *MsgUpdateTransactionHooksResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateTransactionHooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateTransactionHooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateTransactionHooksResponse proto.InternalMessageInfo

type MsgDisableSmartAccount struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *MsgDisableSmartAccount) Reset()         { *m = MsgDisableSmartAccount{} }
func (m *MsgDisableSmartAccount) String() string { return proto.CompactTextString(m) }
func (*MsgDisableSmartAccount) ProtoMessage()    {}
func (*MsgDisableSmartAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2931e7b90fb4027, []int{8}
}
func (m *MsgDisableSmartAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDisableSmartAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDisableSmartAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDisableSmartAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDisableSmartAccount.Merge(m, src)
}
func (m *MsgDisableSmartAccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgDisableSmartAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDisableSmartAccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDisableSmartAccount proto.InternalMessageInfo

func (m *MsgDisableSmartAccount) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type MsgDisableSmartAccountResponse struct {
}

func (m *MsgDisableSmartAccountResponse) Reset()         { *m = MsgDisableSmartAccountResponse{} }
func (m *MsgDisableSmartAccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDisableSmartAccountResponse) ProtoMessage()    {}
func (*MsgDisableSmartAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2931e7b90fb4027, []int{9}
}
func (m *MsgDisableSmartAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDisableSmartAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDisableSmartAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDisableSmartAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDisableSmartAccountResponse.Merge(m, src)
}
func (m *MsgDisableSmartAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDisableSmartAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDisableSmartAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDisableSmartAccountResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateSmartAccount)(nil), "terra.smartaccount.v1.MsgCreateSmartAccount")
	proto.RegisterType((*MsgCreateSmartAccountResponse)(nil), "terra.smartaccount.v1.MsgCreateSmartAccountResponse")
	proto.RegisterType((*MsgAuthorization)(nil), "terra.smartaccount.v1.MsgAuthorization")
	proto.RegisterType((*MsgAuthorizationResponse)(nil), "terra.smartaccount.v1.MsgAuthorizationResponse")
	proto.RegisterType((*MsgUpdateAuthorization)(nil), "terra.smartaccount.v1.MsgUpdateAuthorization")
	proto.RegisterType((*MsgUpdateAuthorizationResponse)(nil), "terra.smartaccount.v1.MsgUpdateAuthorizationResponse")
	proto.RegisterType((*MsgUpdateTransactionHooks)(nil), "terra.smartaccount.v1.MsgUpdateTransactionHooks")
	proto.RegisterType((*MsgUpdateTransactionHooksResponse)(nil), "terra.smartaccount.v1.MsgUpdateTransactionHooksResponse")
	proto.RegisterType((*MsgDisableSmartAccount)(nil), "terra.smartaccount.v1.MsgDisableSmartAccount")
	proto.RegisterType((*MsgDisableSmartAccountResponse)(nil), "terra.smartaccount.v1.MsgDisableSmartAccountResponse")
}

func init() { proto.RegisterFile("terra/smartaccount/v1/tx.proto", fileDescriptor_a2931e7b90fb4027) }

var fileDescriptor_a2931e7b90fb4027 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xbf, 0x6e, 0xd3, 0x40,
	0x18, 0x8f, 0x1b, 0xfe, 0xa4, 0x9f, 0x54, 0x51, 0xb9, 0x4d, 0x70, 0x2d, 0x61, 0x82, 0x41, 0xa2,
	0x20, 0xea, 0x23, 0x69, 0x91, 0x58, 0x03, 0x0c, 0x2c, 0x5e, 0x02, 0x48, 0x88, 0x25, 0xba, 0x38,
	0xc7, 0xc5, 0x6a, 0xec, 0xb3, 0xee, 0xbb, 0x44, 0x29, 0x2c, 0x0c, 0x3c, 0x00, 0x6f, 0xc0, 0x2b,
	0xf0, 0x18, 0x8c, 0x1d, 0x19, 0x51, 0x32, 0xb0, 0xf3, 0x04, 0xc8, 0x76, 0x63, 0x92, 0x70, 0x09,
	0xcd, 0xe6, 0xbb, 0xef, 0xf7, 0xcf, 0x9f, 0x7e, 0x3a, 0x70, 0x14, 0x93, 0x92, 0x12, 0x8c, 0xa8,
	0x54, 0x34, 0x08, 0xc4, 0x30, 0x56, 0x64, 0xd4, 0x20, 0x6a, 0xec, 0x25, 0x52, 0x28, 0x61, 0x56,
	0xb3, 0xb9, 0x37, 0x3f, 0xf7, 0x46, 0x0d, 0x7b, 0x9f, 0x0b, 0x2e, 0x32, 0x04, 0x49, 0xbf, 0x72,
	0xb0, 0x7d, 0x33, 0x10, 0x18, 0x09, 0x24, 0x11, 0xf2, 0x54, 0x24, 0x42, 0x9e, 0x0f, 0xdc, 0x06,
	0x54, 0x7d, 0xe4, 0xcf, 0x25, 0xa3, 0x8a, 0xbd, 0x4a, 0xa5, 0x5a, 0xb9, 0x94, 0x69, 0xc1, 0xf5,
	0x0b, 0x55, 0xcb, 0xa8, 0x1b, 0x87, 0xdb, 0xed, 0xd9, 0xd1, 0xbd, 0x0d, 0xb7, 0xb4, 0x94, 0x36,
	0xc3, 0x44, 0xc4, 0xc8, 0xdc, 0xb7, 0xb0, 0xeb, 0x23, 0x6f, 0x0d, 0x55, 0x5f, 0xc8, 0xf0, 0x03,
	0x55, 0xa1, 0x88, 0xcd, 0x07, 0xb0, 0x1b, 0x88, 0x58, 0x49, 0x1a, 0xa8, 0x0e, 0xed, 0xf5, 0x24,
	0x43, 0xbc, 0xd0, 0xbd, 0x31, 0xbb, 0x6f, 0xe5, 0xd7, 0xe6, 0x01, 0x54, 0xc2, 0x38, 0x54, 0x9d,
	0x08, 0xb9, 0xb5, 0x95, 0x5b, 0xa7, 0x67, 0x1f, 0xb9, 0x6b, 0x83, 0xb5, 0xac, 0x5c, 0xb8, 0x2a,
	0xa8, 0xf9, 0xc8, 0xdf, 0x24, 0x3d, 0xaa, 0xd8, 0xa2, 0xf7, 0xca, 0x5f, 0x31, 0x6d, 0xa8, 0xbc,
	0xa7, 0x83, 0x41, 0x97, 0x06, 0xa7, 0x99, 0x55, 0xa5, 0x5d, 0x9c, 0xcd, 0x7b, 0xb0, 0x43, 0xe7,
	0x65, 0xac, 0x72, 0xbd, 0x7c, 0xb8, 0xdd, 0x5e, 0xbc, 0x74, 0xeb, 0xe0, 0xe8, 0x5d, 0x8b, 0x5c,
	0x5f, 0x0d, 0x38, 0x28, 0x20, 0xaf, 0x25, 0x8d, 0x91, 0x06, 0x29, 0xe0, 0xa5, 0x10, 0xa7, 0xb8,
	0x26, 0x5b, 0x13, 0xaa, 0x89, 0x64, 0x1d, 0xf5, 0x97, 0xd1, 0xe9, 0xa7, 0x14, 0x6b, 0x2b, 0xcb,
	0xb1, 0x97, 0xc8, 0x7f, 0xd5, 0x4e, 0xa0, 0x96, 0x08, 0x54, 0x1a, 0x52, 0x1e, 0x7e, 0x3f, 0x9d,
	0x2e, 0xb3, 0xdc, 0xbb, 0x70, 0x67, 0x65, 0xc0, 0xe2, 0x37, 0x9a, 0xd9, 0x7a, 0x5f, 0x84, 0x48,
	0xbb, 0x83, 0xcb, 0x36, 0x25, 0x5f, 0x8e, 0x86, 0x33, 0x53, 0x6d, 0xfe, 0xbe, 0x02, 0x65, 0x1f,
	0xb9, 0x39, 0x06, 0x53, 0xd3, 0xc1, 0x47, 0x9e, 0xb6, 0xe3, 0x9e, 0xb6, 0x7e, 0xf6, 0xc9, 0x26,
	0xe8, 0x59, 0x02, 0x33, 0x84, 0x9d, 0xc5, 0xb6, 0xdc, 0x5f, 0x2d, 0xb3, 0x00, 0xb4, 0xc9, 0x25,
	0x81, 0x85, 0xd5, 0x47, 0xd8, 0xd3, 0xd5, 0xf3, 0x68, 0xb5, 0x8e, 0x06, 0x6e, 0x3f, 0xd9, 0x08,
	0x5e, 0x98, 0x7f, 0x36, 0xa0, 0xb6, 0xa2, 0x83, 0x8f, 0xff, 0xa7, 0xb8, 0xcc, 0xb0, 0x9f, 0x6e,
	0xca, 0x98, 0xdf, 0x81, 0xae, 0x43, 0x6b, 0x76, 0xa0, 0x81, 0xaf, 0xdb, 0xc1, 0x9a, 0xb6, 0xd9,
	0x57, 0x3f, 0xfd, 0xfa, 0xf6, 0xd0, 0x78, 0xe6, 0x7f, 0x9f, 0x38, 0xc6, 0xf9, 0xc4, 0x31, 0x7e,
	0x4e, 0x1c, 0xe3, 0xcb, 0xd4, 0x29, 0x9d, 0x4f, 0x9d, 0xd2, 0x8f, 0xa9, 0x53, 0x7a, 0x77, 0xcc,
	0x43, 0xd5, 0x1f, 0x76, 0xbd, 0x40, 0x44, 0x24, 0x73, 0x38, 0x8a, 0x44, 0xcc, 0xce, 0x48, 0x20,
	0x24, 0x23, 0xa3, 0x26, 0x19, 0x2f, 0x3e, 0xc7, 0xea, 0x2c, 0x61, 0xd8, 0xbd, 0x96, 0xbd, 0xa4,
	0xc7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x19, 0xa4, 0x1d, 0xcb, 0xb1, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreateSmartAccount defines a method for creating a smart account.
	CreateSmartAccount(ctx context.Context, in *MsgCreateSmartAccount, opts ...grpc.CallOption) (*MsgCreateSmartAccountResponse, error)
	// Authorization defines a method for initializing the wasm authentication contract.
	Authorization(ctx context.Context, in *MsgAuthorization, opts ...grpc.CallOption) (*MsgAuthorizationResponse, error)
	// UpdateAuthorization defines a method for updating the wasm authentication contract.
	UpdateAuthorization(ctx context.Context, in *MsgUpdateAuthorization, opts ...grpc.CallOption) (*MsgUpdateAuthorizationResponse, error)
	// UpdateTransactionHooks defines a method for updating the wasm transaction hooks contract.
	UpdateTransactionHooks(ctx context.Context, in *MsgUpdateTransactionHooks, opts ...grpc.CallOption) (*MsgUpdateTransactionHooksResponse, error)
	// DisableSmartAccountMsg defines a method for converting smart account to basic account.
	DisableSmartAccount(ctx context.Context, in *MsgDisableSmartAccount, opts ...grpc.CallOption) (*MsgDisableSmartAccountResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateSmartAccount(ctx context.Context, in *MsgCreateSmartAccount, opts ...grpc.CallOption) (*MsgCreateSmartAccountResponse, error) {
	out := new(MsgCreateSmartAccountResponse)
	err := c.cc.Invoke(ctx, "/terra.smartaccount.v1.Msg/CreateSmartAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Authorization(ctx context.Context, in *MsgAuthorization, opts ...grpc.CallOption) (*MsgAuthorizationResponse, error) {
	out := new(MsgAuthorizationResponse)
	err := c.cc.Invoke(ctx, "/terra.smartaccount.v1.Msg/Authorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAuthorization(ctx context.Context, in *MsgUpdateAuthorization, opts ...grpc.CallOption) (*MsgUpdateAuthorizationResponse, error) {
	out := new(MsgUpdateAuthorizationResponse)
	err := c.cc.Invoke(ctx, "/terra.smartaccount.v1.Msg/UpdateAuthorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateTransactionHooks(ctx context.Context, in *MsgUpdateTransactionHooks, opts ...grpc.CallOption) (*MsgUpdateTransactionHooksResponse, error) {
	out := new(MsgUpdateTransactionHooksResponse)
	err := c.cc.Invoke(ctx, "/terra.smartaccount.v1.Msg/UpdateTransactionHooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DisableSmartAccount(ctx context.Context, in *MsgDisableSmartAccount, opts ...grpc.CallOption) (*MsgDisableSmartAccountResponse, error) {
	out := new(MsgDisableSmartAccountResponse)
	err := c.cc.Invoke(ctx, "/terra.smartaccount.v1.Msg/DisableSmartAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreateSmartAccount defines a method for creating a smart account.
	CreateSmartAccount(context.Context, *MsgCreateSmartAccount) (*MsgCreateSmartAccountResponse, error)
	// Authorization defines a method for initializing the wasm authentication contract.
	Authorization(context.Context, *MsgAuthorization) (*MsgAuthorizationResponse, error)
	// UpdateAuthorization defines a method for updating the wasm authentication contract.
	UpdateAuthorization(context.Context, *MsgUpdateAuthorization) (*MsgUpdateAuthorizationResponse, error)
	// UpdateTransactionHooks defines a method for updating the wasm transaction hooks contract.
	UpdateTransactionHooks(context.Context, *MsgUpdateTransactionHooks) (*MsgUpdateTransactionHooksResponse, error)
	// DisableSmartAccountMsg defines a method for converting smart account to basic account.
	DisableSmartAccount(context.Context, *MsgDisableSmartAccount) (*MsgDisableSmartAccountResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateSmartAccount(ctx context.Context, req *MsgCreateSmartAccount) (*MsgCreateSmartAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSmartAccount not implemented")
}
func (*UnimplementedMsgServer) Authorization(ctx context.Context, req *MsgAuthorization) (*MsgAuthorizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authorization not implemented")
}
func (*UnimplementedMsgServer) UpdateAuthorization(ctx context.Context, req *MsgUpdateAuthorization) (*MsgUpdateAuthorizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAuthorization not implemented")
}
func (*UnimplementedMsgServer) UpdateTransactionHooks(ctx context.Context, req *MsgUpdateTransactionHooks) (*MsgUpdateTransactionHooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTransactionHooks not implemented")
}
func (*UnimplementedMsgServer) DisableSmartAccount(ctx context.Context, req *MsgDisableSmartAccount) (*MsgDisableSmartAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableSmartAccount not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateSmartAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSmartAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSmartAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/terra.smartaccount.v1.Msg/CreateSmartAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSmartAccount(ctx, req.(*MsgCreateSmartAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Authorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAuthorization)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Authorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/terra.smartaccount.v1.Msg/Authorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Authorization(ctx, req.(*MsgAuthorization))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAuthorization)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/terra.smartaccount.v1.Msg/UpdateAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAuthorization(ctx, req.(*MsgUpdateAuthorization))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateTransactionHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateTransactionHooks)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateTransactionHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/terra.smartaccount.v1.Msg/UpdateTransactionHooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateTransactionHooks(ctx, req.(*MsgUpdateTransactionHooks))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DisableSmartAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDisableSmartAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DisableSmartAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/terra.smartaccount.v1.Msg/DisableSmartAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DisableSmartAccount(ctx, req.(*MsgDisableSmartAccount))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "terra.smartaccount.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSmartAccount",
			Handler:    _Msg_CreateSmartAccount_Handler,
		},
		{
			MethodName: "Authorization",
			Handler:    _Msg_Authorization_Handler,
		},
		{
			MethodName: "UpdateAuthorization",
			Handler:    _Msg_UpdateAuthorization_Handler,
		},
		{
			MethodName: "UpdateTransactionHooks",
			Handler:    _Msg_UpdateTransactionHooks_Handler,
		},
		{
			MethodName: "DisableSmartAccount",
			Handler:    _Msg_DisableSmartAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "terra/smartaccount/v1/tx.proto",
}

func (m *MsgCreateSmartAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateSmartAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateSmartAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateSmartAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateSmartAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateSmartAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAuthorization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAuthorization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAuthorization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InitMsg) > 0 {
		i -= len(m.InitMsg)
		copy(dAtA[i:], m.InitMsg)
		i = encodeVarintTx(dAtA, i, uint64(len(m.InitMsg)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAuthorizationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAuthorizationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAuthorizationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAuthorization) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAuthorization) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAuthorization) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authorization) > 0 {
		for iNdEx := len(m.Authorization) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Authorization[iNdEx])
			copy(dAtA[i:], m.Authorization[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Authorization[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Fallback {
		i--
		if m.Fallback {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAuthorizationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAuthorizationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAuthorizationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateTransactionHooks) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateTransactionHooks) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateTransactionHooks) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PostTransactionHooks) > 0 {
		for iNdEx := len(m.PostTransactionHooks) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PostTransactionHooks[iNdEx])
			copy(dAtA[i:], m.PostTransactionHooks[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.PostTransactionHooks[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PreTransactionHooks) > 0 {
		for iNdEx := len(m.PreTransactionHooks) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PreTransactionHooks[iNdEx])
			copy(dAtA[i:], m.PreTransactionHooks[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.PreTransactionHooks[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateTransactionHooksResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateTransactionHooksResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateTransactionHooksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDisableSmartAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDisableSmartAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDisableSmartAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDisableSmartAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDisableSmartAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDisableSmartAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateSmartAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateSmartAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAuthorization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.InitMsg)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAuthorizationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateAuthorization) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Fallback {
		n += 2
	}
	if len(m.Authorization) > 0 {
		for _, s := range m.Authorization {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateAuthorizationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateTransactionHooks) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.PreTransactionHooks) > 0 {
		for _, s := range m.PreTransactionHooks {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.PostTransactionHooks) > 0 {
		for _, s := range m.PostTransactionHooks {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateTransactionHooksResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDisableSmartAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDisableSmartAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateSmartAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateSmartAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateSmartAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateSmartAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateSmartAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateSmartAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAuthorization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAuthorization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAuthorizationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAuthorizationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAuthorizationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAuthorization) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAuthorization: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAuthorization: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fallback", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Fallback = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authorization", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authorization = append(m.Authorization, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAuthorizationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAuthorizationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAuthorizationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateTransactionHooks) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateTransactionHooks: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateTransactionHooks: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreTransactionHooks", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreTransactionHooks = append(m.PreTransactionHooks, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostTransactionHooks", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostTransactionHooks = append(m.PostTransactionHooks, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateTransactionHooksResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateTransactionHooksResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateTransactionHooksResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDisableSmartAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDisableSmartAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDisableSmartAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDisableSmartAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDisableSmartAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDisableSmartAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
