name: Release

on:
  push:
    branches:
      - main
      - test
      - master
      - 'release/*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'v[0-9]+.[0-9]+.[0-9]+-rc*' # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: macos-latest
            build-type: build-release-arm64
          - os: ubuntu-latest
            build_type: build-release-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build ${{matrix.build_type}}
        run: |
          make ${{matrix.build_type}}
          cp build/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*
