name: Test

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  test-coverage-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.0

      - uses: technote-space/get-diff-action@v6
        id: get-diff
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum

      - name: build
        run: |
          make build

      - name: test & coverage report creation
        run: |
          go test -mod=readonly -timeout 10m -race -coverprofile=coverage.txt -covermode=atomic -tags='ledger test_ledger_mock' ./...
        if: env.GIT_DIFF
        
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt # optional
          fail_ci_if_error: true
        if: env.GIT_DIFF

  test-simulation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.0
      - uses: actions/checkout@v3
      - name: simulate
        run: |
          make simulate